### ISSUE TITLE
希望作者添加富文本组件

### ISSUE THREAD

**Issue by wentaoxie** [vueComponent/ant-design-vue#1292]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前ant-design-vue 加入其他富文本组件会出现一定的冲突

### What does the proposed API look like?
ant-design-vue 封装或者集成其他富文本编辑器

**Comment by sendya** [comment]
antd 的默认组件中暂时没有富文本组件，并且其体积一般比较大。不适合直接集成到组件库中。

你可以参考这个文档，自行引入一个 自己觉得合适的富文本编辑器

https://pro.loacg.com/docs/import

如果要封装实现做为表单元素使用，可以参考 Form 组件的自定义表单组件
也可以在组件内部引入 antd 的主题全局定义变量（`@import "~ant-design-vue/lib/style/index";`）来让第三方富文本组件样式和 antd 一致

例如：
```less
/* 覆盖 quill 默认边框圆角为 ant 默认圆角，用于统一 ant 组件风格 */
.ant-editor-quill {
  /deep/ .ql-toolbar.ql-snow {
    border-radius: @border-radius-base @border-radius-base 0 0;
  }
  /deep/ .ql-container.ql-snow {
    border-radius: 0 0 @border-radius-base @border-radius-base;
  }
}
```
