### ISSUE TITLE
button按钮能否提供更多的type类型，不同颜色的，目前就哪几种很单调，对于后端来说

### ISSUE THREAD

**Issue by xiaoymin** [vueComponent/ant-design-vue#1825]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
button按钮的type希望能多增加几种type类型，不同的颜色种类供开发者选择，对于后端开发来说会方便不少

### What does the proposed API look like?
```html
<a-button type="info">Info</a-button>
```

**Comment by hzyyy** [comment]
不是有相对应的属性么，自定义button color。

**Comment by belongwqz** [comment]
https://www.antdv.com/components/button-cn/没搜索到color，怎么配置的？

**Comment by sendya** [comment]
```
<a-button style="color: red;">Info</a-button>
<a-button style="color: green;">Info</a-button>
```

**Comment by cnguu** [comment]
Customizable button color types:

1. Adding styles to less:

```less
@import "~ant-design-vue/lib/style/themes/default";
@import "~ant-design-vue/es/button/style/mixin";

// warning button style
@btn-warning-color: #fff;
@btn-warning-bg: @warning-color;

.button-variant-warning(@color; @background) {
  .button-color(@color; @background; @background);

  text-shadow: @btn-text-shadow;
  box-shadow: @btn-primary-shadow;

  &:hover,
  &:focus {
    .button-color(@color; ~`colorPalette('@{background}', 5) `; ~`colorPalette('@{background}', 5) `);
  }

  &:active,
  &.active {
    .button-color(@color; ~`colorPalette('@{background}', 7) `; ~`colorPalette('@{background}', 7) `);
  }

  .button-disabled();
}

.btn-warning() {
  .button-variant-warning(@btn-warning-color; @btn-warning-bg);
}

.ant-btn-warning {
  .btn-warning;

  .ant-btn-group {
    &:not(:first-child):not(:last-child) {
      border-right-color: @btn-group-border;
      border-left-color: @btn-group-border;

      &:disabled {
        border-color: @btn-default-border;
      }
    }

    &:first-child {
      &:not(:last-child) {
        border-right-color: @btn-group-border;

        &[disabled] {
          border-right-color: @btn-default-border;
        }
      }
    }
  }

  .ant-btn-group &:last-child:not(:first-child),
  .ant-btn-group & + & {
    border-left-color: @btn-group-border;

    &[disabled] {
      border-left-color: @btn-default-border;
    }
  }
}
```

2. Use in buttons:

```vue
<a-button type="warning">Warning</a-button>
```
