### ISSUE TITLE
Tabs在Safari浏览器13.1（其他版本没有测）切换时Tab里的内容闪现后消失。

### ISSUE THREAD

**Issue by hnjfour** [vueComponent/ant-design-vue#2199]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
macOS Catalina 10.15.4,safari13.1,Ant Design of Vue v1.5.4

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
使用Safari浏览器打开https://ant.design/components/tabs-cn/，切换代码演示的Tab1，Tab2,Tab3,就会看到切换时Tab里的内容闪现后消失。

### What is expected?
解决这个bug.

### What is actually happening?
解决这个bug.

**Comment by tangjinzhou** [comment]
ref https://github.com/ant-design/ant-design/issues/23050

**Comment by tangjinzhou** [comment]
临时方案，添加如下样式：
```css
.ant-tabs .ant-tabs-top-content > .ant-tabs-tabpane, .ant-tabs .ant-tabs-bottom-content > .ant-tabs-tabpane {
	-webkit-backface-visibility: hidden;
} 
```
