### ISSUE TITLE
AutoComplete 自定义输入组件 disabled 属性无效

### ISSUE THREAD

**Issue by shaoye** [vueComponent/ant-design-vue#3140]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
*

### Reproduction link
[https://www.antdv.com/components/auto-complete-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BE%93%E5%85%A5%E7%BB%84%E4%BB%B6](https://www.antdv.com/components/auto-complete-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BE%93%E5%85%A5%E7%BB%84%E4%BB%B6)

### Steps to reproduce
在 textarea 多行的情况下：

若在 a-auto-complete 内设置 disabled 为 true，禁用有效，但灰底样式出错，只覆盖第一行

若在 a-auto-complete 下的 a-textarea 内设置 disabled 为 true，禁用无效，且无灰底样式

### What is expected?
灰底禁用样式覆盖整个textarea

### What is actually happening?
^

**Comment by tangjinzhou** [comment]
临时方案
```css
.ant-select-auto-complete.ant-select .ant-input[disabled] {
    background-color: #f5f5f5;
}
```
