### ISSUE TITLE
🎄 Christmas easter egg 🎄

### ISSUE THREAD

**Issue by tangjinzhou** [vueComponent/ant-design-vue#334]
If you want to remove the Christmas egg,
you can override the css : )

```css
.ant-btn.ant-btn-primary.christmas:before {
  display: none!important;
}
```
