### ISSUE TITLE
Input addonBefore/addonAfter height problem.

### ISSUE THREAD

**Issue by transtone** [vueComponent/ant-design-vue#3765]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
Microsoft Edge

### Reproduction link
[https://2x.antdv.com/components/input-cn](https://2x.antdv.com/components/input-cn)

### Steps to reproduce
官网例子开启 f12 后

### What is expected?
底部对齐

### What is actually happening?
底部不对齐

1.x的表现：
![image](https://user-images.githubusercontent.com/46688/110306103-6838aa00-8038-11eb-8154-158a7f83e1be.png)
2.x 的表现：
![image](https://user-images.githubusercontent.com/46688/110306130-6f5fb800-8038-11eb-96f4-bd5410f16114.png)
![image](https://user-images.githubusercontent.com/46688/110306578-f319a480-8038-11eb-8a28-8bbdb8078eae.png)

**Comment by zkwolf** [comment]
我这没复现出来，开了缩放之类的？

**Comment by transtone** [comment]
没有缩放。
环境：
```
windows 10 Home 20H2
Microsoft Edge 89.0.774.45 
Opera 74.0.3911.203
显示器分辨率 1920x1080  
```
页面右侧打开 f12 之后很明显，不打开也有不平整的问题。

倒是 `Firefox 86.0` 表现正常，不过有 `select 下拉框`重边的问题。firefox: 
![image](https://user-images.githubusercontent.com/46688/110403324-e25c4380-80b7-11eb-9f4f-6480cba56146.png)

**Comment by zkwolf** [comment]
这个提示。。。不太符合我本意，我这复现不出来看看有没有其他人能复现出来

**Comment by xrkffgg** [comment]
😂😂  没 window 机器

**Comment by transtone** [comment]
```
这个提示。。。不太符合我本意
```
您的本意是？

------------------
目前在项目里把边框放到最外层去了：
```less
.ant-input-wrapper.ant-input-group {
  border: 1px solid @border-color-input;
  border-radius: 2px;

  .ant-input-search,
  .ant-input-group-addon {
    border-width: 0;
  }
  .ant-input-group-addon {
    + .ant-input-search {
      border-left: 1px solid @border-color-input;
    }
  }
  .ant-input-search {
    + .ant-input-group-addon {
      border-left: 1px solid @border-color-input;
    }
  }
}
```
