### ISSUE TITLE
The round button and avatar are not centered, whether they are icons or text

### ISSUE THREAD

**Issue by 002269** [vueComponent/ant-design-vue#4397]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
圆形的 button 和 avatar 不管是 icon 还是文本，都不居中。
苹果big sur，chrome,firefox,safari,opera 最新版

### What does the proposed API look like?
绝对居中

**Comment by han1548772930** [comment]
打完包之后 icon 在button里面都是不居中的 dev环境下正常

**Comment by han1548772930** [comment]
加上以下代码可以正常居中
```css
:where(.css-19iuou).ant-btn {
    font-size: 14px;
    height: 32px;
    padding: 4px 15px;
    border-radius: 6px;
    display: inline-flex;
    justify-content: center;
    align-items: center;
}
```

**Comment by han1548772930** [comment]
或者直接全局加上
```css
.ant-btn > span{
    display: inline-flex;
}
```
