### ISSUE TITLE
Cant overwrite default button font size via vue.config.js

### ISSUE THREAD

**Issue by OwenMelbz** [vueComponent/ant-design-vue#476]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
osx 0.14.2, chrome 71.0.3578.9, vue 2.6.4

### Reproduction link
The codesandbox did not seem to support the vue.config.js setup

### Steps to reproduce
When trying to overwrite the font size for a button using the `vue.config.js` e.g.

```js
module.exports = {
    css: {
        loaderOptions: {
            less: {
                modifyVars: {
                    'btn-font-size-lg': '10px',
                    'btn-font-size-sm': '20px',
                    'font-size-base': '60px',
                },
                javascriptEnabled: true,
            },
        },
    },
}
```

Generate a basic default button that produces markup similar to

```html
<button data-v-aa872cac="" type="button" class="ant-btn ant-btn-default" data-v-a5f44b2a=""><span>Your account</span></button>
```

However the CSS that generates is

```css
.ant-btn {
	line-height: 1.499;
	display: inline-block;
	font-weight: 400;
	text-align: center;
	-ms-touch-action: manipulation;
	touch-action: manipulation;
	cursor: pointer;
	background-image: none;
	border: 1px solid transparent;
	white-space: nowrap;
	padding: 0 15px;
	font-size: 60px;
	border-radius: 4px;
	height: 32px;
	-webkit-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	user-select: none;
	-webkit-transition: all .3s cubic-bezier(.645, .045, .355, 1);
	-o-transition: all .3s cubic-bezier(.645, .045, .355, 1);
	transition: all .3s cubic-bezier(.645, .045, .355, 1);
	position: relative;
	-webkit-box-shadow: 0 2px 0 rgba(0, 0, 0, .015);
	box-shadow: 0 2px 0 rgba(0, 0, 0, .015);
	color: rgba(0, 0, 0, .65);
	background-color: #fff;
	border-color: #d9d9d9;
}
```

We're loading the less via `babel.config.js`

```js
module.exports = {
    presets: [
        '@vue/app',
    ],
    plugins: [
        ['import', {
            libraryName: 'ant-design-vue',
            libraryDirectory: 'es',
            style: true,
        }],
    ],
}

```

As you can see it uses the `font-size-base` regardless of what either `btn-font-size-lg` or `btn-font-size-sm` is set to.

### What is expected?
To be able to change the button size via the variables

### What is actually happening?
The `font-size-base` variable is always used regardless

> Note - All over variables such as colours, padding etc work as expected
