### ISSUE TITLE
css variables

### ISSUE THREAD

**Issue by L-Z-Y** [vueComponent/ant-design-vue#4903]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
The current antdv online theme switching requires the introduction of the less compiler. This runtime compilation will affect the performance of the production environment. Can the form of css variables be added later? What should I do if I want to pre-compile multiple sets of theme styles?

### What does the proposed API look like?
null

**Comment by TimVanHerwijnen** [comment]
I'm stuck with this as well. I want to have a dark theme in my Nuxt app but this is impossible using LESS.
I tried using [@nuxtjs/color-mode](https://color-mode.nuxtjs.org/) which uses a `.dark` class at the html element but the theme becomes bugged if I try compiling it like this:
```less
  .dark {
    @import '~ant-design-vue/dist/antd.less';
    @import '~ant-design-vue/lib/style/themes/default.less';
    
    // Not sure what this does... 
    @html-selector: html.light;
    
    /*
    * Ant design vars.
    *
    * To see defaults check the imported default.less
    */
    @primary-color: #556ee6; // Primary color for all components
    // etc...
  }
```
The color switching works but things like the menu become completely bugged when class `.dark` is applied to `<html>` :(
