### ISSUE TITLE
table表格的行的hover效果去除

### ISSUE THREAD

**Issue by nanfb** [vueComponent/ant-design-vue#6456]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
vue版本^3.2.13

### Reproduction link
[https://github.com/nanfb/antd](https://github.com/nanfb/antd)

### Steps to reproduce
通过设置css去除表格列自带的hover效果

### What is expected?
去除hover

### What is actually happening?
在鼠标移出表格的时候hover还是会出现,我无法通过简单的css来去除hover

**Comment by JI4JUN** [comment]
遇到相同的问题

**Comment by lculjt** [comment]
覆盖下 hover状态下会给 td元素添加一个className ant-table-cell-row-hover 可以覆盖下它试试

**Comment by XiaLing233** [comment]
也遇到了这个问题，我的解决方案是：
```css
<style scoped>
:deep(.ant-table-tbody > tr.ant-table-row:hover > td),
:deep(.ant-table-tbody > tr > td.ant-table-cell-row-hover) {
  background: transparent !important;
}
</style>
```
有几个讨论的点：

1. 保持 `scoped` 不变，但不加 `:deep()`，是无法覆盖样式的；
2. 不加 `scoped`，也不加 `:deep()`，对所有的表格都会清除悬浮效果，不管是不是当前 `.vue` 文件中的表格；
3. 不加 !important，也是我一开始检索到的[解决方案](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/8069)，也是无法覆盖的。
